# Generated by Django 5.2.5 on 2025-08-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_alter_hospital_address_alter_hospital_description'),
        ('medications', '0002_initial'),
        ('users', '0009_remove_doctor_age_remove_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='prescriptionschedule',
            options={'ordering': ['time_of_day']},
        ),
        migrations.AddField(
            model_name='medication',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medications.medication'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('hospital', 'name')},
        ),
    ]
