# Generated by Django 5.2.5 on 2025-08-13 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_alter_hospital_address_alter_hospital_description'),
        ('medications', '0003_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospitals.hospital'),
        ),
    ]
