# Generated by Django 5.2.5 on 2025-09-09 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_medication_hospital_and_more'),
        ('users', '0024_alter_doctor_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='prescriptionschedule',
            name='prescription',
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time updated'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time created'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(help_text='The doctor who issued this prescription.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(help_text='The patient who receives this prescription.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.patient'),
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time updated')),
                ('drug_name', models.CharField(help_text='Free text drug name written by doctor.', max_length=255)),
                ('dosage_instruction', models.TextField(help_text="Dosage instructions, e.g., '2 tablets after meal'.")),
                ('frequency_per_day', models.IntegerField(help_text='How many times a day this drug should be taken.')),
                ('duration_days', models.IntegerField(help_text='How many days the drug should be taken.')),
                ('prescription', models.ForeignKey(help_text='The prescription this drug belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='medications.prescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time updated')),
                ('date', models.DateField(help_text='The date this dose was scheduled.')),
                ('scheduled_time', models.TimeField(help_text='Expected time for this dose.')),
                ('taken', models.BooleanField(default=False, help_text='Whether patient took this dose.')),
                ('taken_at', models.DateTimeField(blank=True, help_text='Timestamp when patient marked as taken.', null=True)),
                ('prescription_drug', models.ForeignKey(help_text='The drug schedule this log belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medications.prescriptiondrug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='PrescriptionSchedule',
        ),
    ]
