# Generated by Django 5.2.5 on 2025-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_remove_prescription_medication_and_more'),
        ('users', '0024_alter_doctor_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='prescriptiondrug',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prescription Drug', 'verbose_name_plural': 'Prescription Drugs'},
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique prescription ID in format PRE-XXXXXXXX', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='drug_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique drug ID in format DRG-XXXXXXXX', max_length=15, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_id'], name='medications_prescri_5c9eea_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'patient'], name='medications_doctor__aeda56_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiondrug',
            index=models.Index(fields=['prescription', 'drug_name'], name='medications_prescri_9f9f8a_idx'),
        ),
    ]
