# Generated by Django 5.2.5 on 2025-09-09 21:28

import medications.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(blank=True, db_index=True, default=medications.id_generator.generate_prescription_id, editable=False, help_text='Unique prescription ID in format PRE-XXXXXXXX', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='drug_id',
            field=models.CharField(blank=True, db_index=True, default=medications.id_generator.generate_drug_id, editable=False, help_text='Unique drug ID in format DRG-XXXXXXXX', max_length=15, null=True, unique=True),
        ),
    ]
