# Generated by Django 5.2.5 on 2025-09-09 22:27

import medications.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_prescriptionlog_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlog',
            name='log_id',
            field=models.CharField(blank=True, db_index=True, default=medications.id_generator.generate_log_id, editable=False, help_text='Unique log ID in format LOG-XXXXXXXX', max_length=15, null=True, unique=True),
        ),
    ]
