# Generated by Django 5.2.5 on 2025-09-10 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0009_alter_prescriptionlog_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='frequency_per_day',
            field=models.IntegerField(help_text='How many times a day this drug should be taken.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
