# Generated by Django 5.2.5 on 2025-09-10 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0010_alter_prescriptiondrug_frequency_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='duration_days',
            field=models.IntegerField(help_text='How many days the drug should be taken.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
