# Generated by Django 5.2.5 on 2025-09-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0011_alter_prescriptiondrug_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionlog',
            name='notified',
            field=models.BooleanField(default=False, help_text='Whether a missed reminder has been sent for this dose.'),
        ),
    ]
