# Generated by Django 5.2.5 on 2025-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(help_text='Address of the hospital.'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_email',
            field=models.EmailField(help_text='Contact email of the hospital.', max_length=254),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.CharField(editable=False, help_text='Unique hospital ID in format HOSP-XXXXXXXX', max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(help_text='Name of the hospital.', max_length=255),
        ),
    ]
