# Generated by Django 5.2.5 on 2025-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospital_address_alter_hospital_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique hospital ID in format HOSP-XXXXXXXX', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
