# Generated by Django 5.2.5 on 2025-08-13 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_hospital_id_alter_hospital_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time updated'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time created'),
        ),
    ]
