# Generated by Django 5.2.5 on 2025-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_updated_at_alter_hospital_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(help_text='Description of the hospital.', max_length=500, null=True),
        ),
    ]
