# Generated by Django 5.2.5 on 2025-08-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_hospital_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, help_text='Address of the hospital.', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_email',
            field=models.EmailField(help_text='Contact email of the hospital.', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the hospital.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the hospital.', max_length=255, null=True),
        ),
    ]
