# Generated by Django 5.2.5 on 2025-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_alter_hospital_address_alter_hospital_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(help_text='Name of the hospital.', max_length=255),
        ),
    ]
