# Generated by Django 5.2.5 on 2025-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_alter_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(help_text='Name of the hospital.', max_length=255, unique=True),
        ),
    ]
