# Generated by Django 5.2.5 on 2025-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_alter_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='website_link',
            field=models.URLField(blank=True, help_text='Website link of the hospital.', null=True),
        ),
    ]
