# Generated by Django 5.2.5 on 2025-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_hospital_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, help_text='Address of the hospital.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the hospital.', max_length=2000, null=True),
        ),
    ]
