# Generated by Django 5.2.5 on 2025-09-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
