# Generated by Django 5.2.5 on 2025-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_remove_user_is_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.CharField(editable=False, help_text='Unique doctor ID in format DOC-XXXXXXXX', max_length=13, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(editable=False, help_text='Unique patient ID in format PAT-XXXXXXXX', max_length=13, primary_key=True, serialize=False, unique=True),
        ),
    ]
