# Generated by Django 5.2.5 on 2025-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctor_id_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique doctor ID in format DOC-XXXXXXXX', max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique patient ID in format PAT-XXXXXXXX', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
