# Generated by Django 5.2.5 on 2025-08-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctor_created_at_doctor_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique doctor ID in format DOC-XXXXXXXX', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique patient ID in format PAT-XXXXXXXX', max_length=13, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['license_number'], name='users_docto_license_4e2034_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['doctor_id'], name='users_docto_doctor__0fb33c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='users_patie_patient_f06e8c_idx'),
        ),
    ]
