# Generated by Django 5.2.5 on 2025-08-14 07:26

import django.contrib.postgres.fields
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_doctor_age_remove_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('family_medicine', 'Family Medicine'), ('internal_medicine', 'Internal Medicine'), ('pediatrics', 'Pediatrics'), ('geriatrics', 'Geriatrics'), ('general_surgery', 'General Surgery'), ('orthopedic_surgery', 'Orthopedic Surgery'), ('neurosurgery', 'Neurosurgery'), ('cardiothoracic_surgery', 'Cardiothoracic Surgery'), ('plastic_surgery', 'Plastic Surgery'), ('urology', 'Urology'), ('otolaryngology_ent', 'Otolaryngology (ENT)'), ('ophthalmology', 'Ophthalmology'), ('colon_rectal_surgery', 'Colon and Rectal Surgery'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('infectious_disease', 'Infectious Disease'), ('nephrology', 'Nephrology'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('hematology', 'Hematology'), ('oncology', 'Oncology'), ('anesthesiology', 'Anesthesiology'), ('pathology', 'Pathology'), ('radiology', 'Radiology'), ('emergency_medicine', 'Emergency Medicine'), ('physical_medicine_rehabilitation', 'Physical Medicine and Rehabilitation'), ('allergy_immunology', 'Allergy and Immunology'), ('neurology', 'Neurology'), ('obstetrics_gynecology', 'Obstetrics and Gynecology'), ('psychiatry', 'Psychiatry')], max_length=100), blank=True, default=list, help_text='List of specializations for the doctor. Use field choices from field_choices.py.', size=None, validators=[users.validators.validate_specialization]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, validators=[users.validators.validate_gender]),
        ),
    ]
