# Generated by Django 5.2.5 on 2025-08-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doctor_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
    ]
