# Generated by Django 5.2.5 on 2025-08-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_alter_hospital_address_alter_hospital_description'),
        ('users', '0012_remove_doctor_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='The hospital this doctor belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.hospital', verbose_name='Hospital'),
        ),
    ]
