# Generated by Django 5.2.5 on 2025-08-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_patient_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital', 'Hospital')], default='patient', help_text='Defines whether this user is a patient, doctor, or hospital.', max_length=20),
        ),
    ]
