# Generated by Django 5.2.5 on 2025-08-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP'},
        ),
    ]
