# Generated by Django 5.2.5 on 2025-08-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_user_id_user_users_user_user_id_b5aea9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital', 'Hospital')], default='patient', help_text='Defines whether this user is a patient, doctor, or hospital.', max_length=20),
        ),
    ]
