# Generated by Django 5.2.5 on 2025-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_otp_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='patient', help_text='Defines whether this user is a patient, doctor, or hospital.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='patient', help_text='Defines whether this user is a patient, doctor, or hospital.', max_length=20),
        ),
    ]
