# Generated by Django 5.2.5 on 2025-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_sessiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='expires_at',
            field=models.DateTimeField(default=None),
        ),
    ]
