# Generated by Django 5.2.5 on 2025-08-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_sessiontoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor assigned to this patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.doctor'),
        ),
    ]
