# Generated by Django 5.2.5 on 2025-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_patient_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, help_text='Unique license number of the doctor.', max_length=100, null=True, unique=True),
        ),
    ]
