# Generated by Django 5.2.5 on 2025-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('missed', models.BooleanField(default=False)),
                ('notified_doctor', models.BooleanField(default=False)),
            ],
        ),
    ]
