# Generated by Django 5.2.5 on 2025-08-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherence', '0001_initial'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.prescription'),
        ),
    ]
