# Generated by Django 5.2.5 on 2025-09-09 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0013_alter_hospital_user'),
        ('users', '0024_alter_doctor_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique appointment identifier', unique=True)),
                ('date', models.DateField(help_text='Requested appointment date')),
                ('time', models.TimeField(help_text='Requested appointment time')),
                ('reason', models.TextField(blank=True, help_text='Optional reason or note for the appointment.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Status of the appointment.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor requested for this appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor')),
                ('hospital', models.ForeignKey(help_text='Hospital where this appointment is booked.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospitals.hospital')),
                ('patient', models.ForeignKey(help_text='Patient who booked this appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient')),
            ],
            options={
                'ordering': ['-date', 'time'],
            },
        ),
    ]
